# admin token secret
apiVersion: v1
kind: Secret
metadata:
  name: kong-admin-token-secret
  namespace: kong-datamigration
data:
  token: SkBqaTE5ODVKQGhu
type: Opaque
---

# postgresql secrets
apiVersion: v1
kind: Secret
metadata:
  name: kong-datamigration-postgresql
  namespace: kong-datamigration
data:
  password: QG5HNWxKQGpp
  postgres-password: QG5HNWxKQGpp
type: Opaque
# kubectl apply -f kong-postgresql.yaml -n kong-local
---


apiVersion: v1
kind: Secret
metadata:
  name: kong-enterprise-superuser-password
  namespace: kong-datamigration
data:
  password: SkBqaTE5ODVKQGhu
type: Opaque
